import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Participants from '../components/Participants';
import { getHistoricalMessages } from '../lib/history';
import CombatEffect from '../components/CombatEffects';
import WorldEffect from '@/components/WorldEffects';
import PersonalEffect from '@/components/PersonalEffects';
import RealTimeDice from '@/components/Dice';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faDragon } from '@fortawesome/free-solid-svg-icons';
import PopupButton from '@/components/Menu';

export default function Home(props) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Chaos Engine</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      {/* Header Section */}
      <header className={styles.header}>
      <FontAwesomeIcon icon={faDragon} size="3x" /> {/* Use the imported icon */}
        <h1 className={styles.title}>Chaos Engine</h1>
      </header>

      <main className={styles.main}>
  <div className={styles.WorldBox}>
    <WorldEffect />
  </div>
  <div className={styles.RightBox}>
    <div className={styles.CombatBox}>
      <CombatEffect />
    </div>
    <div className={styles.PersonalBox}>
      <PersonalEffect />
    </div>
  </div>
</main>

     

      {/* Participants Section */}
      <div className={styles.bottomRow}>
      <div className={styles.participants}>
        <div>
        <PopupButton/>
        </div>
        <div>
        <RealTimeDice/>
        </div>
        <Participants />
        </div>
    </div>
    </div>
  );
}

export async function getStaticProps() {
  const historicalMessages = await getHistoricalMessages();

  return {
    props: {
      history: historicalMessages || [],
    },
    revalidate: 10,
  };
}
